# Generated by Django 4.1.3 on 2022-12-15 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_itemquery_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="mail_sent",
            field=models.BooleanField(default=False),
        ),
    ]
